"""Parse 文本.txt + the kin JSON into JS data files.

Outputs:
  data/readingContent.js  — CHAPTER_CONTENT[<chapter-id>] = sections[]
  data/wordLibrary.js     — WORDS list with full structure (KIN populated from JSON)
"""
import re, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TXT_PATH  = os.path.join(ROOT, "文本.txt")
JSON_PATH = os.path.join(ROOT, "stage0_kin_insertion_candidates_with_2phrases_ALL.json")

# Chapter id used in the JS data must match the ids in data/mockChapters.js.
CHAPTER_ID = {
    "1":  "universe",
    "2":  "earth-history",
    "3":  "africa",
    "4":  "antarctica",
    "5":  "australia-pacific",
    "6":  "oceans",            # source: "The Indian Ocean and the Atlantic"
    "7":  "south-america",
    "8":  "asia",
    "9":  "europe",
    "10": "north-america",
}


def parse_chapters(text):
    chap_re = re.compile(r"^# Stage 0, Chapter (\d+):\s*(.+)$", re.M)
    matches = list(chap_re.finditer(text))
    chapters = []
    for i, m in enumerate(matches):
        num   = m.group(1)
        title = m.group(2).strip()
        start = m.end()
        end   = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body  = text[start:end]
        sections = parse_sections(body, num)
        chapters.append({
            "number": num,
            "title":  title,
            "id":     CHAPTER_ID.get(num, f"chapter-{num}"),
            "sections": sections,
        })
    return chapters


def parse_sections(chap_body, chap_num):
    sec_re = re.compile(r"^## (\d+\.\d+)\s+(.+)$", re.M)
    matches = list(sec_re.finditer(chap_body))
    sections = []
    for i, m in enumerate(matches):
        num   = m.group(1)
        title = m.group(2).strip()
        start = m.end()
        end   = matches[i + 1].start() if i + 1 < len(matches) else len(chap_body)
        body  = chap_body[start:end].strip()
        # Extract quiz items
        quiz = []
        for q in re.finditer(r"\*\*Q(\d+):\*\*\s*(.+?)\s*\n\s*\*\*A\1:\*\*\s*(.+)", body):
            quiz.append({"q": q.group(2).strip(), "a": q.group(3).strip()})
        # Reading text = body minus Q&A lines
        reading = re.sub(r"\*\*Q\d+:.+", "", body, flags=re.S).strip()
        sentences = split_sentences(reading)
        sections.append({
            "number": num,
            "title":  title,
            "blocks": sentences,                # reveal blocks
            "quiz":   quiz,
            "audio_prefix": f"assets/audio/ch{chap_num}/{num}",  # used to derive per-block audio
        })
    return sections


def split_sentences(paragraph):
    """Split a paragraph into sentence-level reveal blocks while keeping
    punctuation. We treat ". ", "? ", "! " as sentence breaks (not inside
    abbreviations, but the text doesn't have many)."""
    # Normalise newlines / spacing
    paragraph = re.sub(r"\s+", " ", paragraph).strip()
    # Insert a marker after sentence-ending punctuation followed by space + capital
    parts = re.split(r"(?<=[.!?])\s+(?=[A-Z])", paragraph)
    return [p.strip() for p in parts if p.strip()]


def parse_words():
    with open(JSON_PATH) as f:
        data = json.load(f)
    by_head = {}
    for e in data:
        head = e["target_head"]
        kin_entry = {
            "word":     e["child_word"],
            "zh":       e["child_zh"],
            "phrases": [
                {"en": e["phrase_1"], "zh": e["phrase_1_zh"]},
                {"en": e["phrase_2"], "zh": e["phrase_2_zh"]},
            ],
        }
        if head not in by_head:
            by_head[head] = {
                "id":       head,
                "word":     head,
                "pos":      "",
                "meaning":  "",         # not provided in JSON
                "family":   [],
                "friend":   [],
                "kin":      [],
                "example":  "",
                "exampleZh": "",
            }
        by_head[head]["kin"].append(kin_entry)
    # Sort alphabetically for stable diffs.
    return sorted(by_head.values(), key=lambda w: w["id"])


def js_literal(obj, indent=0):
    """Render a Python value as a compact JS expression."""
    return json.dumps(obj, ensure_ascii=False, indent=2)


def main():
    with open(TXT_PATH, encoding="utf-8") as f:
        text = f.read()
    chapters = parse_chapters(text)
    words    = parse_words()

    # ------- write reading content -------
    out_path = os.path.join(ROOT, "data", "readingContent.js")
    content = {c["id"]: c for c in chapters}
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED by tools/build_data.py. Do not hand-edit.\n"
                "   Source: 文本.txt\n */\n")
        f.write("const CHAPTER_CONTENT = " + js_literal(content) + ";\n\n")
        f.write("function getChapterContent(id) { return CHAPTER_CONTENT[id]; }\n")
    print(f"wrote {out_path}  ({sum(len(c['sections']) for c in chapters)} sections "
          f"across {len(chapters)} chapters)")

    # ------- write word library -------
    out_path = os.path.join(ROOT, "data", "wordLibrary.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED by tools/build_data.py. Do not hand-edit.\n"
                "   Source: stage0_kin_insertion_candidates_with_2phrases_ALL.json\n"
                "   NOTE: family / friend / meaning / example are intentionally empty —\n"
                "   the source JSON contains only KIN relations. Hand-curated words\n"
                "   may override this in data/mockWords.js.\n */\n")
        f.write("const WORD_LIBRARY = " + js_literal(words) + ";\n\n")
        f.write("const WORD_LIBRARY_BY_ID = Object.fromEntries(WORD_LIBRARY.map(w => [w.id, w]));\n")
        f.write("function libWord(id) { return WORD_LIBRARY_BY_ID[id]; }\n")
    print(f"wrote {out_path}  ({len(words)} words)")


if __name__ == "__main__":
    main()
